#!/bin/sh

start() {
  if [ -x /usr/bin/docker ]; then
    /usr/bin/docker -d >> /var/log/docker.log 2>&1 &
  fi
}

stop() {
  if [ -f /var/run/docker.pid ]; then
    kill `cat /var/run/docker.pid`
    if [ -f /var/run/docker.pid ]; then
      rm -rf /var/run/docker.pid
    fi
  fi
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    sleep 3
    start
    ;;
*)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

