name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             token: ${{ secrets.NOTIFY_ACTION_TOKEN }}
             recipients: |
                  Support Contract=@rclone/support
